# Generated by Django 3.1.7 on 2021-03-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
