# Generated by Django 3.1.7 on 2021-03-11 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 20, 36, 47, 750974)),
        ),
        migrations.AddField(
            model_name='image',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 20, 36, 47, 750974)),
        ),
    ]
