# Generated by Django 3.1.7 on 2021-03-12 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210310_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 12, 42, 33, 116228)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 12, 42, 33, 116228)),
        ),
    ]
